#!/bin/bash -e
if [ ! -e .git ]; then
    if [ "$pwd" -eq '/' ]; then
        exit 1
    fi
    cd ..
fi
./run_problem.py --test-all
# check commit message
msg=$(git show -s HEAD --format="%s%n%n%b" | python hooks/format-commit-message.py)
git commit --amend -m "$msg" 2> /dev/null
git push --no-verify
exit 1
